name: Bun CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      # Clean up node_modules and package-lock.json
      - run: rm -rf node_modules package-lock.json
      # Install dependencies with --no-optional to skip problematic optional dependencies
      - run: bun install --no-optional
      # Build the project
      - run: bun run build
